### ISSUE TITLE
Xcode 6 compatibility?

### ISSUE THREAD

**Issue by lbrndnr** [jonathanpenn/ui-auto-monkey#10]
Hi Jonathan,

Thanks for this great tool :)
I could get it to work some time ago but failing to do so now and I can't figure out why. I always get "An error occurred while trying to run the script." error in the log messages.
I did everything just like you in the tutorial, as far as I can tell at least. 

Do you know what I could be doing wrong? Or is this not working with the current Xcode version?

Thanks in advance :)

**Comment by Arunr1** [comment]
I am trying to run monkey test on iOS 8.1 simulator (Xcode 6.1) but the script auto stops without doing anything. Need help, anybody !!

**Comment by sandip08888** [comment]
Hi,
I am new to ios testing. My question may stupid one but please reply back.
**Is it possible to test any .ipa installed on ipad / iphone using UI auto monkey?
I have only Xcode in my system but no project / source code to corresponding that .ipa file.**

If possible then please guide me.
