### ISSUE TITLE
How to write a scroll UIScrollView test?

### ISSUE THREAD

**Issue by xhzengAIB** [jonathanpenn/ui-auto-monkey#12]
Hi！@jonathanpenn 
I have main page, Take a UIScrollView in this page.

Jack

**Comment by jonathanpenn** [comment]
Hey @xhzengAIB, I'm not quite sure what you're asking for. You can interact with a scroll view using a drag gesture on the element. But the Auto Monkey's whole purpose is to randomly interact with the screen and it wasn't written to talk to specific elements in a certain way. You could certainly write your own custom gesture support [with these instructions](https://github.com/jonathanpenn/ui-auto-monkey#custom-use). But it's still going to be random.

**Comment by xhzengAIB** [comment]
Hi! @jonathanpenn My English is very bad, I'm really sorry.  
Thank you very much for your reply, I know you can write custom gestures, but how should I write about a random location sliding UIScrollview gesture?

Jack

**Comment by jonathanpenn** [comment]
No worries, @xhzengAIB. Glad to help! Though it sounds like this script won't do what you want. It's for sending touch events to the entire screen and doesn't target specific views.

But if you wanted to still do "drag" events all over the screen, I'd recommend looking into the `dragFromToForDuration` method on `UIATarget` at Apple's documentation:

https://developer.apple.com/library/ios/documentation/ToolsLanguages/Reference/UIATargetClassReference/#//apple_ref/javascript/instm/UIATarget/dragFromToForDuration

That should get you on the right path.

**Comment by xhzengAIB** [comment]
Hi！@jonathanpenn 
Thank you! I got it.
