### ISSUE TITLE
UIAutoMonkey.RELEASE_THE_MONKEY() is undefined

### ISSUE THREAD

**Issue by tfrank64** [jonathanpenn/ui-auto-monkey#26]
Every time I run the script in Xcode 7 or 6, I get the error: 

UIScript threw an uncaught JavaScript error: UIAutoMonkey.RELEASE_THE_MONKEY is not a function. (In 'UIAutoMonkey.RELEASE_THE_MONKEY()', 'UIAutoMonkey.RELEASE_THE_MONKEY' is undefined) on line 468 of New%20Script

I fixed this by using an older version of UIAutoMonkey, so instead of using:
`UIAutoMonkey.RELEASE_THE_MONKEY();`

I use the following and it works:
`(new UIAutoMonkey()).RELEASE_THE_MONKEY();`

Is this expected behavior?

**Comment by joamafer** [comment]
+1, I'm facing the same problem

**Comment by Ricardo1980** [comment]
+1, have the same problem.

**Comment by dqshll** [comment]
+1, thank for your solution

**Comment by Rhinomcd** [comment]
+1, Same issue here.

**Comment by nishanov** [comment]
@tfrank64 thanks for solution, maybe you should send PR with fix? :)

**Comment by tfrank64** [comment]
@nishanov I will do that soon unless I hear otherwise from any primary project developers.

**Comment by jonathanpenn** [comment]
Is this resolved by #27?

**Comment by tfrank64** [comment]
Yes, thanks for merging.
